#!/bin/bash
# setup.sh
# natsuume-statusline プラグインを ~/.claude/settings.json の statusLine.command に登録する。
# 既存の statusLine 設定 (含 settings.json 全体) はタイムスタンプ付きでバックアップする。

set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
  echo "[natsuume-statusline] jq が見つかりません。jq をインストールしてから再実行してください。" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENTRYPOINT="$PLUGIN_ROOT/statusline/entrypoint.sh"

if [ ! -f "$ENTRYPOINT" ]; then
  echo "[natsuume-statusline] エントリポイントが見つかりません: $ENTRYPOINT" >&2
  exit 1
fi

# Claude Code は実行ビットを保ったまま展開する保証が無いので、ここで明示的に付与する。
chmod +x "$ENTRYPOINT" "$PLUGIN_ROOT/statusline/main.sh" 2>/dev/null || true

SETTINGS_DIR="$HOME/.claude"
SETTINGS="$SETTINGS_DIR/settings.json"
mkdir -p "$SETTINGS_DIR"

# settings.json が存在しない、または空ファイルなら最低限の JSON を作る。
if [ ! -s "$SETTINGS" ]; then
  echo '{}' > "$SETTINGS"
fi

# 中身が壊れた JSON だった場合は backup して空オブジェクトに置き換える前に中断。
# 自動修復はスコープ外 (誤った状態を黙って上書きしない)。
if ! jq empty "$SETTINGS" >/dev/null 2>&1; then
  echo "[natsuume-statusline] $SETTINGS が壊れています (jq parse 失敗)。手動で修復してから再実行してください。" >&2
  exit 1
fi

# 同秒内に複数回実行された場合に前のバックアップを上書きしないよう、
# 既存と衝突した場合は連番を付けて回避する。
TIMESTAMP=$(date +%Y%m%dT%H%M%S)
BACKUP="$SETTINGS_DIR/settings.natsuume-statusline-backup.$TIMESTAMP.json"
suffix=0
while [ -e "$BACKUP" ]; do
  suffix=$((suffix + 1))
  BACKUP="$SETTINGS_DIR/settings.natsuume-statusline-backup.$TIMESTAMP-$suffix.json"
done
cp "$SETTINGS" "$BACKUP"

# プラグインがスペースやシェルメタ文字を含むパスに置かれていても安全に呼び出せるよう、
# パスを single-quote で囲み、内部の `'` を `'\''` でエスケープしてから組み立てる。
single_quote() { printf '%s' "$1" | sed "s/'/'\\\\''/g"; }

# settings.json の statusLine.command に焼き込むパスは、plugin update で消える version
# 固有の cache パス (~/.claude/plugins/cache/<marketplace>/<plugin>/<VERSION>/...) を
# 直接指してはならない (issue #51 / Claude Code bug #52079: statusLine.command では
# ${CLAUDE_PLUGIN_ROOT} 等が展開されず、settings には安定した絶対パスを書く必要がある)。
# cache 配下から実行された場合は ~/.claude 配下に安定した薄い wrapper を設置し、settings は
# その wrapper を指す。wrapper は実行時に「version dir の親」(update を跨いで安定) から
# 現在 active な version の entrypoint を解決するため、/plugin update 後も再 setup なしで
# statusline が追従する。wrapper 本体の設置は settings.json 更新の「前」に行う (順序が重要:
# 先に settings を wrapper へ向けてから wrapper 書き込みに失敗すると、settings が存在しない
# wrapper を指したまま残り statusline が無言で壊れる = 修正対象の #51 を再現してしまうため)。
case "$PLUGIN_ROOT" in
  */plugins/cache/*)
    VERSIONS_DIR="$(dirname "$PLUGIN_ROOT")"
    WRAPPER="$SETTINGS_DIR/natsuume-statusline-entrypoint.sh"
    NEW_COMMAND="bash '$(single_quote "$WRAPPER")'"
    REGISTERED_TARGET="$WRAPPER"
    REGISTER_MODE="wrapper"
    ;;
  *)
    # 非 cache (ローカル clone 等の安定パス): wrapper は不要で entrypoint を直接指す。
    NEW_COMMAND="bash '$(single_quote "$ENTRYPOINT")'"
    REGISTERED_TARGET="$ENTRYPOINT"
    REGISTER_MODE="direct"
    ;;
esac
# --- (1) wrapper mode のときは settings 更新の「前」に安定 wrapper を atomic 設置する。---
# 順序が重要: wrapper を先に置くことで、 wrapper 書き込み失敗時は settings 未変更 (= 無害)
# で済む。 先に settings を wrapper へ向けてから wrapper 書き込みに失敗すると、 settings が
# 存在しない wrapper を指したまま残り statusline が無言で壊れる (#51 の再現になる)。
if [ "$REGISTER_MODE" = "wrapper" ]; then
  vq_versions=$(single_quote "$VERSIONS_DIR")
  vq_fallback=$(single_quote "$ENTRYPOINT")
  umask 077
  WRAPPER_TMP=$(mktemp "$WRAPPER.XXXXXX")
  trap 'rm -f "$WRAPPER_TMP"' EXIT
  {
    printf '#!/bin/bash\n'
    printf '# Auto-generated by /natsuume-statusline:setup. このファイルにバージョンを\n'
    printf '# 焼き込まないこと。settings.json はこの安定パスを指し、本 wrapper が実行時に\n'
    printf '# 現在 active な version の entrypoint を解決することで plugin update に追従する\n'
    printf '# (cache パスは version 固有: issue #51 / Claude Code bug #52079)。\n'
    printf "VERSIONS_DIR='%s'\n" "$vq_versions"
    printf "FALLBACK_ENTRYPOINT='%s'\n" "$vq_fallback"
    cat <<'WRAPPER_BODY'

# version dir の親 (VERSIONS_DIR) は plugin update を跨いで安定。そこから「現在 active な
# version」の entrypoint を解決する。active = 最も最近インストールされた version = mtime
# 最新。ただし plugins update は複数 version dir に同一 mtime を付けることがある (実測で
# 同時刻の version dir が複数共存) ため、mtime 同着は最も高い semver で tie-break する。
# これで forward update / downgrade / GC 前の orphan のいずれでも誤選択しない。semver は
# X.Y.Z の数値 3 フィールドのみを対象とし、prerelease 等の suffix dir は無視する (純数値
# 比較で prerelease が GA より上位に来る事故を防ぐ)。sort は -V 非依存の POSIX numeric
# field sort で macOS の bash 3.2 / BSD sort / busybox でも動作する。
dir_mtime() {
  # GNU / busybox は `stat -c %Y`、BSD / macOS は `stat -f %m`。
  stat -c %Y "$1" 2>/dev/null || stat -f %m "$1" 2>/dev/null
}

resolve_entrypoint() {
  [ -d "$VERSIONS_DIR" ] || return 1
  best_entry="" best_mtime="" best_v=""
  for d in "$VERSIONS_DIR"/*/; do
    entry="${d}statusline/entrypoint.sh"
    [ -f "$entry" ] || continue
    v=$(basename "$d")
    case "$v" in
      ''|*[!0-9.]*) continue ;;  # 純数値 X.Y.Z 以外 (prerelease 等) はスキップ
    esac
    m=$(dir_mtime "$d")
    [ -n "$m" ] || m=0
    if [ -z "$best_entry" ]; then
      best_entry="$entry"; best_mtime="$m"; best_v="$v"
      continue
    fi
    take=0
    if [ "$m" -gt "$best_mtime" ]; then
      take=1
    elif [ "$m" -eq "$best_mtime" ]; then
      higher=$(printf '%s\n%s\n' "$best_v" "$v" | sort -t. -k1,1n -k2,2n -k3,3n | tail -n1)
      [ "$higher" = "$v" ] && [ "$v" != "$best_v" ] && take=1
    fi
    if [ "$take" -eq 1 ]; then
      best_entry="$entry"; best_mtime="$m"; best_v="$v"
    fi
  done
  [ -n "$best_entry" ] || return 1
  printf '%s' "$best_entry"
}

ENTRY=$(resolve_entrypoint)
if [ -z "$ENTRY" ] || [ ! -f "$ENTRY" ]; then
  ENTRY="$FALLBACK_ENTRYPOINT"
fi
exec bash "$ENTRY" "$@"
WRAPPER_BODY
  } > "$WRAPPER_TMP"
  chmod +x "$WRAPPER_TMP" 2>/dev/null || true
  mv "$WRAPPER_TMP" "$WRAPPER"
  trap - EXIT
fi

# --- (2) settings.json の statusLine.command を NEW_COMMAND に差し替える。---
# settings.json はトークン等を含む可能性があるため world-readable な temp を作らない。
# また `mktemp` の default (/tmp) はターゲットと別 FS の可能性があり、その場合
# 後段の `mv` が copy+unlink フォールバックで非アトミックになる。同一ディレクトリに
# temp を作って rename(2) 一発で差し替える。
umask 077
TMP=$(mktemp "$SETTINGS.XXXXXX")
trap 'rm -f "$TMP"' EXIT

jq --arg cmd "$NEW_COMMAND" '
  .statusLine = {
    "type": "command",
    "command": $cmd
  }
' "$SETTINGS" > "$TMP"

# 念のため出力 JSON が valid か再検証してから差し替える。
if ! jq empty "$TMP" >/dev/null 2>&1; then
  echo "[natsuume-statusline] 生成された JSON が不正です。settings.json は変更しません。" >&2
  exit 1
fi

mv "$TMP" "$SETTINGS"
trap - EXIT

cat <<MSG
[natsuume-statusline] セットアップ完了。

  settings.json   : $SETTINGS
  バックアップ    : $BACKUP
  登録ターゲット  : $REGISTERED_TARGET
  エントリポイント: $ENTRYPOINT

statusLine.command を更新しました。次回以降のプロンプト更新からプラグイン版の statusline が使われます。
MSG

if [ "$REGISTER_MODE" = "wrapper" ]; then
  cat <<MSG

plugin cache 配下で実行されたため、安定した wrapper を設置し settings.json はこれを指します:
  $REGISTERED_TARGET

wrapper が実行時に最新版 entrypoint を解決するため、/plugin update 後も再 setup なしで
statusline が追従します (別 marketplace から入れ直した / wrapper を削除した場合のみ再 setup が必要)。
MSG
else
  cat <<MSG

cache 配下ではない安定パスから実行されたため、wrapper を介さず entrypoint を直接登録しました。
MSG
fi

cat <<MSG

元の設定に戻したい場合は、上記のバックアップで settings.json を上書きしてください:
  cp '$BACKUP' '$SETTINGS'
MSG
